// Generated by gencpp from file youbot/ControlCommandResponse.msg
// DO NOT EDIT!


#ifndef YOUBOT_MESSAGE_CONTROLCOMMANDRESPONSE_H
#define YOUBOT_MESSAGE_CONTROLCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace youbot
{
template <class ContainerAllocator>
struct ControlCommandResponse_
{
  typedef ControlCommandResponse_<ContainerAllocator> Type;

  ControlCommandResponse_()
    : response(false)  {
    }
  ControlCommandResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::youbot::ControlCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youbot::ControlCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommandResponse_

typedef ::youbot::ControlCommandResponse_<std::allocator<void> > ControlCommandResponse;

typedef boost::shared_ptr< ::youbot::ControlCommandResponse > ControlCommandResponsePtr;
typedef boost::shared_ptr< ::youbot::ControlCommandResponse const> ControlCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::youbot::ControlCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::youbot::ControlCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::youbot::ControlCommandResponse_<ContainerAllocator1> & lhs, const ::youbot::ControlCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::youbot::ControlCommandResponse_<ContainerAllocator1> & lhs, const ::youbot::ControlCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace youbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::youbot::ControlCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::youbot::ControlCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youbot::ControlCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youbot::ControlCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youbot::ControlCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youbot::ControlCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::youbot::ControlCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::youbot::ControlCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::youbot::ControlCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "youbot/ControlCommandResponse";
  }

  static const char* value(const ::youbot::ControlCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::youbot::ControlCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
;
  }

  static const char* value(const ::youbot::ControlCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::youbot::ControlCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youbot::ControlCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::youbot::ControlCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUBOT_MESSAGE_CONTROLCOMMANDRESPONSE_H
