// Generated by gencpp from file rt_gene/MSG_Headpose.msg
// DO NOT EDIT!


#ifndef RT_GENE_MESSAGE_MSG_HEADPOSE_H
#define RT_GENE_MESSAGE_MSG_HEADPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt_gene
{
template <class ContainerAllocator>
struct MSG_Headpose_
{
  typedef MSG_Headpose_<ContainerAllocator> Type;

  MSG_Headpose_()
    : subject_id()
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  MSG_Headpose_(const ContainerAllocator& _alloc)
    : subject_id(_alloc)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _subject_id_type;
  _subject_id_type subject_id;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::rt_gene::MSG_Headpose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_gene::MSG_Headpose_<ContainerAllocator> const> ConstPtr;

}; // struct MSG_Headpose_

typedef ::rt_gene::MSG_Headpose_<std::allocator<void> > MSG_Headpose;

typedef boost::shared_ptr< ::rt_gene::MSG_Headpose > MSG_HeadposePtr;
typedef boost::shared_ptr< ::rt_gene::MSG_Headpose const> MSG_HeadposeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_gene::MSG_Headpose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_gene::MSG_Headpose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt_gene::MSG_Headpose_<ContainerAllocator1> & lhs, const ::rt_gene::MSG_Headpose_<ContainerAllocator2> & rhs)
{
  return lhs.subject_id == rhs.subject_id &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt_gene::MSG_Headpose_<ContainerAllocator1> & lhs, const ::rt_gene::MSG_Headpose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt_gene

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_Headpose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_Headpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_Headpose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a67796c87e69b7ea1ff5e7bb87e7034";
  }

  static const char* value(const ::rt_gene::MSG_Headpose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a67796c87e69b7eULL;
  static const uint64_t static_value2 = 0xa1ff5e7bb87e7034ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_gene/MSG_Headpose";
  }

  static const char* value(const ::rt_gene::MSG_Headpose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string subject_id\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rt_gene::MSG_Headpose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subject_id);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MSG_Headpose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_gene::MSG_Headpose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_gene::MSG_Headpose_<ContainerAllocator>& v)
  {
    s << indent << "subject_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.subject_id);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_GENE_MESSAGE_MSG_HEADPOSE_H
