// Generated by gencpp from file rt_gene/MSG_Landmarks.msg
// DO NOT EDIT!


#ifndef RT_GENE_MESSAGE_MSG_LANDMARKS_H
#define RT_GENE_MESSAGE_MSG_LANDMARKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt_gene
{
template <class ContainerAllocator>
struct MSG_Landmarks_
{
  typedef MSG_Landmarks_<ContainerAllocator> Type;

  MSG_Landmarks_()
    : subject_id()
    , landmarks()  {
    }
  MSG_Landmarks_(const ContainerAllocator& _alloc)
    : subject_id(_alloc)
    , landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _subject_id_type;
  _subject_id_type subject_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::rt_gene::MSG_Landmarks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_gene::MSG_Landmarks_<ContainerAllocator> const> ConstPtr;

}; // struct MSG_Landmarks_

typedef ::rt_gene::MSG_Landmarks_<std::allocator<void> > MSG_Landmarks;

typedef boost::shared_ptr< ::rt_gene::MSG_Landmarks > MSG_LandmarksPtr;
typedef boost::shared_ptr< ::rt_gene::MSG_Landmarks const> MSG_LandmarksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_gene::MSG_Landmarks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt_gene::MSG_Landmarks_<ContainerAllocator1> & lhs, const ::rt_gene::MSG_Landmarks_<ContainerAllocator2> & rhs)
{
  return lhs.subject_id == rhs.subject_id &&
    lhs.landmarks == rhs.landmarks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt_gene::MSG_Landmarks_<ContainerAllocator1> & lhs, const ::rt_gene::MSG_Landmarks_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt_gene

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_Landmarks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_Landmarks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_Landmarks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6e6840b2076b49500e303fc6790d231";
  }

  static const char* value(const ::rt_gene::MSG_Landmarks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6e6840b2076b495ULL;
  static const uint64_t static_value2 = 0x00e303fc6790d231ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_gene/MSG_Landmarks";
  }

  static const char* value(const ::rt_gene::MSG_Landmarks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string subject_id\n"
"float64[] landmarks\n"
;
  }

  static const char* value(const ::rt_gene::MSG_Landmarks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subject_id);
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MSG_Landmarks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_gene::MSG_Landmarks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_gene::MSG_Landmarks_<ContainerAllocator>& v)
  {
    s << indent << "subject_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.subject_id);
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_GENE_MESSAGE_MSG_LANDMARKS_H
