// Generated by gencpp from file rt_gene/MSG_Gaze.msg
// DO NOT EDIT!


#ifndef RT_GENE_MESSAGE_MSG_GAZE_H
#define RT_GENE_MESSAGE_MSG_GAZE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt_gene
{
template <class ContainerAllocator>
struct MSG_Gaze_
{
  typedef MSG_Gaze_<ContainerAllocator> Type;

  MSG_Gaze_()
    : subject_id()
    , phi(0.0)
    , theta(0.0)  {
    }
  MSG_Gaze_(const ContainerAllocator& _alloc)
    : subject_id(_alloc)
    , phi(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _subject_id_type;
  _subject_id_type subject_id;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::rt_gene::MSG_Gaze_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_gene::MSG_Gaze_<ContainerAllocator> const> ConstPtr;

}; // struct MSG_Gaze_

typedef ::rt_gene::MSG_Gaze_<std::allocator<void> > MSG_Gaze;

typedef boost::shared_ptr< ::rt_gene::MSG_Gaze > MSG_GazePtr;
typedef boost::shared_ptr< ::rt_gene::MSG_Gaze const> MSG_GazeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_gene::MSG_Gaze_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_gene::MSG_Gaze_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt_gene::MSG_Gaze_<ContainerAllocator1> & lhs, const ::rt_gene::MSG_Gaze_<ContainerAllocator2> & rhs)
{
  return lhs.subject_id == rhs.subject_id &&
    lhs.phi == rhs.phi &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt_gene::MSG_Gaze_<ContainerAllocator1> & lhs, const ::rt_gene::MSG_Gaze_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt_gene

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_gene::MSG_Gaze_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_gene::MSG_Gaze_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_gene::MSG_Gaze_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7b3cda7766f7ea47f1ac64e0a9b76eb";
  }

  static const char* value(const ::rt_gene::MSG_Gaze_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7b3cda7766f7ea4ULL;
  static const uint64_t static_value2 = 0x7f1ac64e0a9b76ebULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_gene/MSG_Gaze";
  }

  static const char* value(const ::rt_gene::MSG_Gaze_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string subject_id\n"
"float64 phi\n"
"float64 theta\n"
;
  }

  static const char* value(const ::rt_gene::MSG_Gaze_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subject_id);
      stream.next(m.phi);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MSG_Gaze_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_gene::MSG_Gaze_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_gene::MSG_Gaze_<ContainerAllocator>& v)
  {
    s << indent << "subject_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.subject_id);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_GENE_MESSAGE_MSG_GAZE_H
